@url= https://localhost:3002
// @url= https://175.24.36.114:3002

### 定时任务(清空活跃度)
### get {{url}}/user/resetActive

### 总用户
get {{url}}/user/totalUser

### 用户性别比例
get {{url}}/user/genderRate

### 今日新增用户
get {{url}}/user/todayAddUser

### 在线离线比例(管理员)
get {{url}}/user/liveRate

### 获取当日用户活跃排行榜(前10位)
get {{url}}/user/activeUsers

### 获取近七天增长用户(管理员)
get {{url}}/user/sevenDaysAddUser

### 获取今日新增内容(管理员)
get {{url}}/content/todayContent

### 获取今日新增内容增长率(管理员)
get {{url}}/content/todayContentRate

### 获取所有内容(管理员)
get {{url}}/content/allContentsRoot

### 获取今日新增主题(管理员)
get {{url}}/contentType/todayContentType

### 启用禁用用户(管理员)
get {{url}}/user/isStopUser?id=15&flag=0

### 封禁 0 解禁 1 内容(管理员)
get {{url}}/content/isStopContent?id=2&flag=2

### 导出用户信息excel
get {{url}}/user/userExcel

### 管理员登录
get {{url}}/user/rootLogin?phone=123456&password=123456
# Content-Type: application/json

# {
#     "phone": "123456",
#     "password": "123456"
# }


### 管理员注册
#get {{url}}/user/rootRegister?phone=15188211507&password=!123456.&name=梦涛(管理员)


### 用户重置密码
put {{url}}/user/updateUserPwd?phone=111


### 用户获取个人信息 
get {{url}}/user/getInfo?uid=undefined
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTA.ZlWTaouJ8-kpAjtWMXCDK7alaCpkWtEAjvtgyBRnJl8

### 用户登录
post {{url}}/user/login?phone=15188211507&password=123456

### 修改密码
put {{url}}/user/updatePwd?oldPassword=12345678&newPassword=123456
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTQ.yFAAWaBeP7rq_XztWB2A4PHDG58SmQ4L2Z9DLdh0d7Y

### 用户注册
post {{url}}/user/register


### 创建主题
post {{url}}/theme/createTheme?name=那年我十八&status=0
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTQ.yFAAWaBeP7rq_XztWB2A4PHDG58SmQ4L2Z9DLdh0d7Y


### 用户获取创建主题
get {{url}}/theme/getThemeByUid
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTQ.yFAAWaBeP7rq_XztWB2A4PHDG58SmQ4L2Z9DLdh0d7Y

### 获取所有公开主题
get {{url}}/theme/getOpenTheme

### 获取某个主题
get {{url}}/theme/getThemeById?id=11

### 获取主题列表
get {{url}}/theme/getThemeList
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTQ.yFAAWaBeP7rq_XztWB2A4PHDG58SmQ4L2Z9DLdh0d7Y

### 管理员获取所有主题
### get {{url}}/contentType/allContentType
// get {{url}}/contentType/allContentType?status=1&nickName=李


### 修改某一主题
# post {{url}}/contentType/updateContentType?id=1



### 删除(恢复)主题 status 0(删除) 1(恢复) 2(名称违规 管理员封禁)
# get {{url}}/contentType/isdeleteContentType?id=2&status=0

### 创建内容
post {{url}}/content/createContent?context=这是一个跨界打劫你，你却无力反击的时代&img=https://kangaroo-app.oss-cn-hangzhou.aliyuncs.com/1571905601259.png&status=0&flag=3&is_comment=1&tid=11&address=杭州市下城区跨贸小镇
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTQ.yFAAWaBeP7rq_XztWB2A4PHDG58SmQ4L2Z9DLdh0d7Y


### 用户获取所有发表内容
get {{url}}/content/getContentByUid?status=9
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTQ.yFAAWaBeP7rq_XztWB2A4PHDG58SmQ4L2Z9DLdh0d7Y

### 用户获取收藏内容
get {{url}}/content/getMySaveContent
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTQ.yFAAWaBeP7rq_XztWB2A4PHDG58SmQ4L2Z9DLdh0d7Y

### 获取公开主题下的内容
get {{url}}/content/getOpencontentByTid?tid=17

### 获取所有公开内容
get {{url}}/content/getAllContents

### 获取所有评论 (管理员)
get {{url}}/comment/allComment

### 获取所有收藏 (管理员)
get {{url}}/save/allSave

### 获取所有点赞 (管理员)
get {{url}}/mark/allMark

### 获取文章评论
get {{url}}/comment/commentByCid?id=3

### 获取某一内容收藏数
get {{url}}/save/saveCountByCid?id=3

### 获取某一内容点赞数
get {{url}}/mark/markCountByCid?id=3

### 用户获取某一内容是否点赞
get {{url}}/mark/markSign?cid=6
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTU.dppZzUZLcDlW4rnAzW9MCeOu7KytUK3-oNLN90BNEio

### 重置密码
get {{url}}/user/resetPwd?phone=123456

### 待审核内容
get {{url}}/content/waitContentRoots

### 待审核主题
get {{url}}/theme/waitThemeRoots

### 待审核内容，主题数量
get {{url}}/content/waitDealCount


